Cleaned up some redundany/duplicated dependencies

diff --git a/marco/Pkgfile b/marco/Pkgfile
--- a/marco/Pkgfile
+++ b/marco/Pkgfile
@@ -1,7 +1,7 @@
 # Description: The MATE window manager, a fork of metacity
 # URL: http://www.mate-desktop.org/
 # Maintainer: Matt Housh, jaeger at crux dot ninja
-# Depends on: libcanberra zenity desktop-file-utils mate-desktop libcanberra
+# Depends on: libcanberra zenity mate-desktop
 
 name=marco
 version=1.28.1
@@ -10,8 +10,8 @@ source=(http://pub.mate-desktop.org/releases/${version:0:4}/$name-$version.tar.x
 
 build() {
   if [ ! -f /usr/lib/pkgconfig/libcanberra-gtk3.pc ]; then
-		echo -e "\n\nlibcanberra-gtk3.pc not found, libcanberra needs to be rebuilt after gtk3 installation.\n\n"
-		exit 1
+    echo -e "\n\nlibcanberra-gtk3.pc not found, libcanberra needs to be rebuilt after gtk3 installation.\n\n"
+    exit 1
   fi
   cd $name-$version
   ./configure --prefix=/usr \
